In [3]:
#importing dependencies 
import pandas as pd
from pathlib import Path

In [4]:
#File path for PLACES__ZCTA_Data__GIS_Friendly_Format___2023_release.csv
zcta_path= Path("resources/PLACES__ZCTA_Data__GIS_Friendly_Format___2023_release.csv")

In [5]:
#Pandas Dataframe for our imported csv 
med_df = pd.read_csv(zcta_path)
med_df.head()

,ZCTA5,TotalPopulation,ACCESS2_CrudePrev,ACCESS2_Crude95CI,ARTHRITIS_CrudePrev,ARTHRITIS_Crude95CI,BINGE_CrudePrev,BINGE_Crude95CI,BPHIGH_CrudePrev,BPHIGH_Crude95CI,...,COGNITION_Crude95CI,MOBILITY_CrudePrev,MOBILITY_Crude95CI,SELFCARE_CrudePrev,SELFCARE_Crude95CI,INDEPLIVE_CrudePrev,INDEPLIVE_Crude95CI,DISABILITY_CrudePrev,DISABILITY_Crude95CI,Geolocation
0,1001,16769,4.1,"( 3.4, 5.0)",33.7,"(30.1, 37.4)",15.6,"(13.2, 18.2)",33.8,"(30.2, 37.4)",...,"(11.7, 15.2)",14.3,"(12.3, 16.4)",3.5,"( 3.0, 3.9)",7.6,"( 6.6, 8.8)",31.5,"(28.1, 35.3)",POINT (-72.62581515 42.06255509)
1,1002,29049,4.7,"( 3.9, 5.6)",18.9,"(16.4, 21.6)",17.3,"(14.5, 20.5)",20.6,"(18.0, 23.5)",...,"(14.1, 18.5)",9.2,"( 8.0, 10.5)",2.9,"( 2.6, 3.2)",7.8,"( 6.9, 8.9)",26.5,"(23.2, 30.2)",POINT (-72.4509085 42.38758794)
2,1003,10372,6.9,"( 5.8, 8.3)",5.5,"( 4.4, 6.7)",19.3,"(16.0, 22.9)",9.4,"( 7.7, 11.3)",...,"(26.6, 33.2)",4.0,"( 3.4, 4.6)",2.2,"( 1.9, 2.5)",13.2,"(11.6, 14.8)",35.2,"(30.7, 39.7)",POINT (-72.52475918 42.39190728)
3,1005,5079,3.8,"( 2.9, 4.9)",26.4,"(23.6, 29.6)",17.4,"(15.1, 20.0)",28.0,"(25.1, 31.0)",...,"(11.1, 15.1)",10.7,"( 9.0, 12.6)",2.9,"( 2.5, 3.4)",6.4,"( 5.4, 7.6)",24.9,"(21.8, 28.5)",POINT (-72.10611705 42.42009493)
4,1007,14649,3.3,"( 2.6, 4.1)",25.2,"(21.7, 28.7)",18.1,"(15.2, 21.4)",24.5,"(21.2, 28.0)",...,"( 9.2, 12.3)",9.4,"( 7.9, 11.0)",2.5,"( 2.2, 2.9)",5.4,"( 4.6, 6.2)",21.3,"(18.2, 24.6)",POINT (-72.40031647 42.27869142)

In [8]:
med_df.shape

(32409, 77)

In [6]:
med_df.describe()

,ZCTA5,TotalPopulation,ACCESS2_CrudePrev,ARTHRITIS_CrudePrev,BINGE_CrudePrev,BPHIGH_CrudePrev,BPMED_CrudePrev,CANCER_CrudePrev,CASTHMA_CrudePrev,CERVICAL_CrudePrev,...,SLEEP_CrudePrev,STROKE_CrudePrev,TEETHLOST_CrudePrev,HEARING_CrudePrev,VISION_CrudePrev,COGNITION_CrudePrev,MOBILITY_CrudePrev,SELFCARE_CrudePrev,INDEPLIVE_CrudePrev,DISABILITY_CrudePrev
count,32409.000000,32409.000000,31435.000000,31435.000000,31435.000000,31435.000000,31435.000000,31435.000000,31435.000000,32400.000000,...,32409.000000,31435.000000,32230.000000,31435.000000,31435.000000,31435.000000,31435.000000,31435.000000,31435.000000,31435.000000
mean,49782.933228,9525.967972,10.275470,27.775397,16.555912,34.504053,76.840951,7.195063,10.447613,81.756827,...,33.510241,3.377792,15.394604,7.548427,5.359790,14.311589,15.006747,4.214070,8.459691,31.114003
std,27388.795154,13732.183671,5.585422,5.791190,2.901248,6.622420,6.849616,1.627359,1.171503,3.803663,...,4.018388,0.915926,5.729988,2.020044,2.164639,3.858948,4.721557,1.574772,2.683255,6.967069
min,1001.000000,50.000000,1.700000,1.900000,2.000000,5.100000,10.900000,0.600000,5.100000,41.900000,...,20.400000,0.300000,3.300000,1.100000,1.300000,5.500000,0.800000,0.400000,2.400000,9.900000
25%,27214.000000,789.000000,6.800000,24.700000,14.700000,30.400000,75.200000,6.400000,9.700000,80.000000,...,30.800000,2.800000,11.500000,6.200000,3.900000,11.500000,11.800000,3.200000,6.600000,26.200000
50%,49783.000000,2914.000000,8.700000,28.400000,16.500000,34.500000,78.200000,7.300000,10.400000,82.100000,...,33.300000,3.300000,14.600000,7.500000,4.900000,13.800000,14.600000,3.900000,8.000000,30.700000
75%,72067.000000,13152.000000,12.200000,31.400000,18.100000,38.600000,80.400000,8.100000,11.100000,84.000000,...,35.900000,3.900000,18.600000,8.800000,6.200000,16.550000,17.800000,4.900000,9.800000,35.600000
max,99929.000000,113916.000000,59.600000,61.600000,40.600000,68.300000,95.200000,23.100000,20.700000,90.900000,...,51.200000,12.500000,53.900000,26.900000,24.300000,42.400000,47.800000,18.600000,30.500000,66.600000

In [9]:
# Get Independent Variable Data
test_df = pd.read_csv("resources/AGI+coords_data.csv")

# As per the Metric Definitions, all money columns here are in thousands of dollars

# Also dropped 3 rows because some ZIPs didn't have coordinates, apparently. Columns renamed for personal convenience
test_df = test_df.drop(["Unnamed: 0", "index"], axis=1).dropna(axis="index", how="any").rename(columns={"N2":"Total Individuals", "A02650":"Total Income Amount"})
test_df

,STATE,ZIPCODE,Total Individuals,Total Income Amount,Total Income per Individual,lng,lat
0,MS,38738,140.0,5.770000e+02,4.121429,-90.53653,33.93049
1,MO,64147,280.0,1.591000e+03,5.682143,-94.54688,38.85387
2,SD,57794,390.0,3.206000e+03,8.220513,-102.40695,43.12071
3,TN,37140,390.0,3.239000e+03,8.305128,-87.65245,35.86345
4,MT,59444,270.0,2.321000e+03,8.596297,-111.34881,48.65227
...,...,...,...,...,...,...,...
27637,CA,94301,14750.0,1.527798e+07,1035.795390,-122.14992,37.44424
27638,CA,94027,5820.0,6.971688e+06,1197.884536,-122.20313,37.45399
27639,FL,33480,9050.0,1.466156e+07,1620.061768,-80.04075,26.69796
27640,CA,94104,1510.0,2.990505e+06,1980.466887,-122.40211,37.79144
27641,FL,33109,520.0,1.578682e+06,3035.926924,-80.14197,25.76160

In [10]:
# We'll ignore any of the CI columns and keep the ZCTA5 column, so there should be 31 columns left

# Extract all Prevalence columns
prev_df = med_df.filter(like="Prev")

# Can't forget to get the ZIP Code data or else there would be nothing to merge on
prev_df.insert(0, "ZIPCODE", med_df.loc[:, "ZCTA5"])

# Drop nulls
a_df = prev_df.dropna(axis="index", how="any")

# Join data on ZIP Codes, drop nulls again just in case, and rename them for presentation purposes
medical_df = test_df.merge(a_df, how="left", on="ZIPCODE").dropna(axis="index", how="any")\
.rename(columns=
        {# Health Outcomes
         "ARTHRITIS_CrudePrev":"Arthritis", "BPHIGH_CrudePrev":"High Blood Pressure", "CANCER_CrudePrev":"(Non-Skin) Cancer", 
         "CASTHMA_CrudePrev":"Current Asthma", "CERVICAL_CrudePrev":"Cervical Cancer (Adult Women)", "CHD_CrudePrev":"Coronary Heart Disease",
         "COPD_CrudePrev":"Chronic Obstructive Pulmonary Disease", "DEPRESSION_CrudePrev":"Depression", "DIABETES_CrudePrev":"Diabetes",
         "HIGHCHOL_CrudePrev":"High Cholesterol", "KIDNEY_CrudePrev":"Chronic Kidney Disease", "OBESITY_CrudePrev":"Obesity", "STROKE_CrudePrev":"Stroke", "TEETHLOST_CrudePrev":"All Teeth Lost (Older Adults)",
         # Prevention 
         "ACCESS2_CrudePrev":"Lacking Health Insurance", "BPMED_CrudePrev":"Taking Medicine for High Blood Pressure",
         "CHECKUP_CrudePrev":"Routine Health Checkups", "CHOLSCREEN_CrudePrev":"Cholesterol Screening", 
         "COLON_SCREEN_CrudePrev":"FOBT/Colon Screening (Older Adults)",  "COREM_CrudePrev":"Core Clinical Prevention (Older Men)", "COREW_CrudePrev":"Core Clinical Prevention (Older Women)",
         "DENTAL_CrudePrev":"Dentist Visits", "MAMMOUSE_CrudePrev":"Mammography (Older Women)",
         # Health Risk Behaviors
         "BINGE_CrudePrev":"Binge Drinking", "CSMOKING_CrudePrev":"Currently Smoking", "LPA_CrudePrev":"No Leisure-Time Physical Activity",
         "SLEEP_CrudePrev":"Less than 7 Hours of Sleep", 
         # Health Status
         "GHLTH_CrudePrev":"'Fair' or 'Poor' Self-Rated Health Status", "MHLTH_CrudePrev":"'Poor' Self-Rated Mental Health Status", 
         "PHLTH_CrudePrev":"'Poor' Self-Rated Physical Health Status"
        })

# Note: Each of the Health Outcomes columns is the "Crude Prevalence" of that particular health phenomenon
# Note: Unless mentioned otherwise, these stats are measured for adults
medical_df

,STATE,ZIPCODE,Total Individuals,Total Income Amount,Total Income per Individual,lng,lat,Lacking Health Insurance,Arthritis,Binge Drinking,...,Less than 7 Hours of Sleep,Stroke,All Teeth Lost (Older Adults),HEARING_CrudePrev,VISION_CrudePrev,COGNITION_CrudePrev,MOBILITY_CrudePrev,SELFCARE_CrudePrev,INDEPLIVE_CrudePrev,DISABILITY_CrudePrev
0,MS,38738,140.0,5.770000e+02,4.121429,-90.53653,33.93049,24.8,17.6,18.4,...,41.0,3.2,28.3,6.0,9.5,23.6,15.7,6.7,12.1,40.9
1,MO,64147,280.0,1.591000e+03,5.682143,-94.54688,38.85387,14.4,8.5,20.6,...,37.4,1.0,21.7,2.6,4.4,20.7,5.7,2.0,9.2,28.6
2,SD,57794,390.0,3.206000e+03,8.220513,-102.40695,43.12071,20.3,24.1,17.0,...,35.4,5.2,41.8,11.4,14.9,27.5,22.8,10.0,18.1,50.2
3,TN,37140,390.0,3.239000e+03,8.305128,-87.65245,35.86345,20.5,16.7,20.5,...,43.2,2.4,22.9,5.1,5.5,18.4,11.3,3.9,8.2,32.7
4,MT,59444,270.0,2.321000e+03,8.596297,-111.34881,48.65227,11.8,26.4,21.5,...,32.7,3.2,17.5,8.9,5.4,16.2,13.6,4.4,8.8,32.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27631,WA,98039,3090.0,2.322736e+06,751.694498,-122.23963,47.63308,3.4,25.3,15.2,...,22.9,2.5,4.3,5.6,2.5,7.3,7.8,2.1,4.1,18.4
27633,WY,83014,3060.0,2.617969e+06,855.545425,-110.93746,43.45800,7.7,21.5,20.2,...,26.0,2.1,8.0,5.9,2.7,8.8,8.0,2.2,4.4,19.8
27634,CA,94301,14750.0,1.527798e+07,1035.795390,-122.14992,37.44424,3.3,19.3,14.6,...,24.0,2.3,4.7,5.4,2.5,6.8,7.4,1.9,3.9,17.4
27635,CA,94027,5820.0,6.971688e+06,1197.884536,-122.20313,37.45399,3.0,23.4,14.1,...,24.7,2.6,4.9,6.3,2.7,6.9,9.0,2.1,4.2,19.3
27637,CA,94104,1510.0,2.990505e+06,1980.466887,-122.40211,37.79144,7.5,20.3,12.5,...,30.2,3.2,10.3,7.0,5.2,10.5,12.3,3.6,6.4,26.0

In [ ]:
#dropping the irrelevant features and features that are age restricted
# dropping state as well
medical_df = medical_df.drop(columns=['STATE', 'lng', 'lat','Core Clinical Prevention (Older Men)',
       'Core Clinical Prevention (Older Women)','Mammography (Older Women)','All Teeth Lost (Older Adults)'], axis =1)

medical_df.columns

Index(['ZIPCODE', 'Total Individuals', 'Total Income Amount',
       'Total Income per Individual', 'Lacking Health Insurance', 'Arthritis',
       'Binge Drinking', 'High Blood Pressure',
       'Taking Medicine for High Blood Pressure', '(Non-Skin) Cancer',
       'Current Asthma', 'Cervical Cancer (Adult Women)',
       'Coronary Heart Disease', 'Routine Health Checkups',
       'Cholesterol Screening', 'FOBT/Colon Screening (Older Adults)',
       'Chronic Obstructive Pulmonary Disease', 'Currently Smoking',
       'Dentist Visits', 'Depression', 'Diabetes',
       ''Fair' or 'Poor' Self-Rated Health Status', 'High Cholesterol',
       'Chronic Kidney Disease', 'No Leisure-Time Physical Activity',
       ''Poor' Self-Rated Mental Health Status', 'Obesity',
       ''Poor' Self-Rated Physical Health Status',
       'Less than 7 Hours of Sleep', 'Stroke', 'HEARING_CrudePrev',
       'VISION_CrudePrev', 'COGNITION_CrudePrev', 'MOBILITY_CrudePrev',
       'SELFCARE_CrudePrev', 'INDEPLIVE_CrudePrev', 'DISABILITY_CrudePrev'],
      dtype='object')

In [90]:
medical_df.describe()

,ZIPCODE,Total Individuals,Total Income Amount,Total Income per Individual,lng,lat,Lacking Health Insurance,Arthritis,Binge Drinking,High Blood Pressure,...,Less than 7 Hours of Sleep,Stroke,All Teeth Lost (Older Adults),HEARING_CrudePrev,VISION_CrudePrev,COGNITION_CrudePrev,MOBILITY_CrudePrev,SELFCARE_CrudePrev,INDEPLIVE_CrudePrev,DISABILITY_CrudePrev
count,26684.000000,26684.000000,2.668400e+04,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,...,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000,26684.000000
mean,49413.818768,10019.320941,4.386216e+05,38.531524,-90.562915,39.110943,10.229508,27.654550,16.582030,34.390680,...,33.470450,3.340215,15.139582,7.415301,5.285223,14.155456,14.855887,4.163068,8.356240,30.785774
std,27348.822109,13668.210604,7.689043e+05,34.035660,14.222422,4.583923,5.560125,5.322031,2.728713,6.177027,...,3.984164,0.838326,5.517054,1.841191,2.075344,3.694370,4.473248,1.501949,2.567867,6.793506
min,1001.000000,140.000000,5.770000e+02,4.121429,-161.906710,19.306120,1.700000,3.800000,3.200000,7.400000,...,21.000000,0.500000,3.300000,1.500000,1.400000,5.500000,1.900000,0.800000,2.700000,10.800000
25%,26148.500000,1120.000000,3.344500e+04,25.880956,-96.736785,35.868785,6.800000,24.500000,14.800000,30.300000,...,30.800000,2.800000,11.300000,6.100000,3.900000,11.400000,11.600000,3.100000,6.500000,25.900000
50%,49941.500000,3590.000000,1.160665e+05,31.431141,-88.273545,39.706315,8.600000,28.300000,16.500000,34.300000,...,33.300000,3.300000,14.500000,7.300000,4.800000,13.700000,14.500000,3.900000,8.000000,30.500000
75%,71358.500000,14152.500000,5.242355e+05,40.213156,-79.997225,42.207120,12.200000,31.200000,18.100000,38.300000,...,35.800000,3.800000,18.400000,8.600000,6.200000,16.400000,17.600000,4.900000,9.800000,35.400000
max,99901.000000,128670.000000,1.527798e+07,1980.466887,-67.018340,67.254350,59.600000,49.800000,31.400000,60.400000,...,51.200000,9.000000,47.500000,20.400000,23.800000,35.100000,37.500000,16.100000,25.100000,59.200000

In [12]:
# Import the required modules for classification report 
# Import required libraries
# Import the modules
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

## Building the Linear Regression Model

In [98]:
#Creating labels set for (y) from "zipcode" coulumn and features (X) for the rest of the data
X = medical_df["Total Income per Individual"].values.reshape(-1,1)

X

array([[   4.12142857],
       [   5.68214286],
       [   8.22051282],
       ...,
       [1035.79538983],
       [1197.88453608],
       [1980.46688748]])

In [99]:
X.shape

(26684, 1)

In [100]:
y = medical_df["(Non-Skin) Cancer"]

y.shape

(26684,)

In [101]:
y

0        2.6
1        1.5
2        4.3
3        2.9
4        6.6
        ...
27631    8.6
27633    6.8
27634    7.7
27635    8.9
27637    6.1
Name: (Non-Skin) Cancer, Length: 26684, dtype: float64

In [102]:
from sklearn.linear_model import LinearRegression
# Create a model with scikit-learn
model = LinearRegression()

In [103]:
# Fit the data into the model
model.fit(X, y)

LinearRegression()

In [104]:
# Display the slope
print(f"Model's slope: {model.coef_}")

Model's slope: [0.00141295]

In [105]:
# Display the y-intercept
print(f"Model's y-intercept: {model.intercept_}")

Model's y-intercept: 7.1146955653531805

In [106]:
# Display the model's best fit line formula
print(f"Model's formula: y = {model.intercept_} + {model.coef_[0]}X")

Model's formula: y = 7.1146955653531805 + 0.0014129533218948803X

In [107]:
# Displaying line for regression 
print(f"Model's formula: y = {model.intercept_} + {model.coef_[0]} * 10000")

# Predicted risk with GDP 10 
y_8 = model.intercept_ + model.coef_[0] * 10000

# Display the prediction
print(f"Predicted risk  {y_8:.2f}")

Model's formula: y = 7.1146955653531805 + 0.0014129533218948803 * 10000
Predicted risk  21.24

In [108]:
# Make predictions using the X set
predicted_y_values = model.predict(X)

predicted_y_values

array([7.12051895, 7.12272417, 7.12631077, ..., 8.5782261 , 8.8072505 ,
       9.91300283])

In [110]:
# Create a copy of the original data
medical_df_predicted = medical_df[["Total Income Amount","(Non-Skin) Cancer"]]

# Add a column with the predicted salary values
medical_df_predicted["cancer_risk_predicted"] = predicted_y_values

# Display sample data
medical_df_predicted.head()

/var/folders/w9/1qf67rw90dgbqv7rkw546lvh0000gn/T/ipykernel_50360/2088460528.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medical_df_predicted["cancer_risk_predicted"] = predicted_y_values

   Total Income Amount  (Non-Skin) Cancer  cancer_risk_predicted
0             577.0000                2.6               7.120519
1            1591.0000                1.5               7.122724
2            3206.0000                4.3               7.126311
3            3239.0001                2.9               7.126430
4            2321.0001                6.6               7.126842